// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3QkC9nQ0zdiJ8S8fGOjNyMo5nvkeEv1s',
    appId: '1:27361311705:web:eb064df9f63e53d52af7c8',
    messagingSenderId: '27361311705',
    projectId: 'authcheck-dee76',
    authDomain: 'authcheck-dee76.firebaseapp.com',
    storageBucket: 'authcheck-dee76.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwcZASgNSB5fX9UZ-gUZWMyCM9STIdLtU',
    appId: '1:27361311705:android:7721aab89f4321752af7c8',
    messagingSenderId: '27361311705',
    projectId: 'authcheck-dee76',
    storageBucket: 'authcheck-dee76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJleqTOrQe6-dcExFrCRjg2EQaQPOU7wE',
    appId: '1:27361311705:ios:b10da2ff7a3fbaec2af7c8',
    messagingSenderId: '27361311705',
    projectId: 'authcheck-dee76',
    storageBucket: 'authcheck-dee76.appspot.com',
    iosClientId: '27361311705-j3i25d3utlprn1s4mrrbettc3dj76qc9.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthCheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJleqTOrQe6-dcExFrCRjg2EQaQPOU7wE',
    appId: '1:27361311705:ios:b10da2ff7a3fbaec2af7c8',
    messagingSenderId: '27361311705',
    projectId: 'authcheck-dee76',
    storageBucket: 'authcheck-dee76.appspot.com',
    iosClientId: '27361311705-j3i25d3utlprn1s4mrrbettc3dj76qc9.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthCheck',
  );
}
